### ISSUE TITLE
add concept list to concepticon

### ISSUE THREAD

**Issue by LinguList** [lexibank/naganorgyalrongic#3]
I think it is worthwhile adding this list, even if it is not completely mapped.

**Comment by SimonGreenhill** [comment]
Is this done?

**Comment by LinguList** [comment]
No.

**Comment by tresoldi** [comment]
The dataset is already using the concept list.  Many concepts are unmapped, but it was reviewed about 6 months ago and in most cases it was due to concepts missing in Concepticon (at least the first is still not there, "eyeball"). I think I reviewed it with Nathanel, maybe he remembers.

**Comment by tresoldi** [comment]
Pinging @Schweikhard

**Comment by LinguList** [comment]
Ah, I forgot the concept list was already added to concepticon.
