### ISSUE TITLE
Problems in the profile

### ISSUE THREAD

**Issue by tresoldi** [lexibank/naganorgyalrongic#4]
@LinguList sorry for the errors, but now you have some problems of not referring to the normalized BIPA (e.g., the ejection is marked with U+2019 and not U+02BC).

I will apply the "profile linter" I'm using to finalize WOLD, apply it here, and submit a PR.

**Comment by LinguList** [comment]
Okay, but that was not introduced by myself, I didn't touch upon ejection markers.

**Comment by LinguList** [comment]
If you use the "linter", please use also CLTS, as CLTS is doing the correction automatically, if it can detect problems.

**Comment by SimonGreenhill** [comment]
Can this be closed?

**Comment by tresoldi** [comment]
Let me check, I don't remember anymore...

**Comment by tresoldi** [comment]
Yes, it is solved. Some tones are unknown but actually right, it is one of the many things I should be taking care in CLTS.

I augmented and sorted the profile nonetheless. Closing the issue.
